# Generated by Django 5.0.6 on 2026-04-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='image_url',
            field=models.TextField(blank=True),
        ),
    ]
