# Generated by Django 5.0.6 on 2026-04-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_init'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
