# Generated by Django 5.0.6 on 2026-04-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_links',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
