# Generated by Django 5.0.6 on 2026-04-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_profile_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('freelancer', 'Freelancer'), ('client', 'Client')], default='', max_length=16),
        ),
    ]
