# Generated by Django 5.0.6 on 2026-04-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='portfolio_images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='gig',
            name='portfolio_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='gig',
            name='what_you_get',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='savedgig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
