# Generated by Django 5.0.6 on 2026-04-25 23:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0002_gig_portfolio_images_gig_portfolio_links_and_more'),
        ('jobs', '0003_job_sample_links'),
        ('orders', '0003_delivery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='gig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='gigs.gig'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('funded', 'Funded'), ('delivered', 'Delivered'), ('disputed', 'Disputed'), ('approved', 'Approved'), ('released', 'Released'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=24),
        ),
        migrations.AlterField(
            model_name='order',
            name='tier',
            field=models.CharField(blank=True, choices=[('basic', 'Basic'), ('pro', 'Pro')], max_length=10),
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=16)),
                ('admin_notes', models.TextField(blank=True)),
                ('resolution', models.CharField(blank=True, choices=[('refund', 'Refund Client'), ('release', 'Release to Freelancer')], max_length=16)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dispute', to='orders.order')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes_raised', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'disputes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.PositiveIntegerField()),
                ('delivery_days', models.PositiveSmallIntegerField()),
                ('message', models.TextField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_sent', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='jobs.jobpost')),
            ],
            options={
                'db_table': 'offers',
                'ordering': ['-created_at'],
                'unique_together': {('job', 'freelancer')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='offer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='orders.offer'),
        ),
    ]
