# Generated by Django 5.0.6 on 2026-04-26 01:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('offer_received', 'Offer Received'), ('offer_accepted', 'Offer Accepted'), ('offer_rejected', 'Offer Rejected'), ('order_funded', 'Order Funded'), ('order_delivered', 'Order Delivered'), ('order_approved', 'Order Approved'), ('order_rejected', 'Order Rejected'), ('order_disputed', 'Order Disputed'), ('order_released', 'Order Released'), ('dispute_resolved', 'Dispute Resolved')], max_length=32)),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField(blank=True)),
                ('data', models.JSONField(default=dict)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
